// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using layihe.DataContext;

namespace layihe.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20220619173332_newflightig")]
    partial class newflightig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("layihe.Models.ArrivialCity", b =>
                {
                    b.Property<int>("ArrivialCityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewFlightId")
                        .HasColumnType("int");

                    b.HasKey("ArrivialCityId");

                    b.HasIndex("NewFlightId");

                    b.ToTable("ArrivialCities");
                });

            modelBuilder.Entity("layihe.Models.DepartureCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewFlightId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewFlightId");

                    b.ToTable("DepartureCities");
                });

            modelBuilder.Entity("layihe.Models.NewFlight", b =>
                {
                    b.Property<int>("NewFlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArrivialCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivialTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("DepartureCityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("SeatingCapacity")
                        .HasColumnType("int");

                    b.HasKey("NewFlightId");

                    b.ToTable("NewFlights");
                });

            modelBuilder.Entity("layihe.Models.ArrivialCity", b =>
                {
                    b.HasOne("layihe.Models.NewFlight", null)
                        .WithMany("ArrivialCities")
                        .HasForeignKey("NewFlightId");
                });

            modelBuilder.Entity("layihe.Models.DepartureCity", b =>
                {
                    b.HasOne("layihe.Models.NewFlight", null)
                        .WithMany("DepartureCities")
                        .HasForeignKey("NewFlightId");
                });

            modelBuilder.Entity("layihe.Models.NewFlight", b =>
                {
                    b.Navigation("ArrivialCities");

                    b.Navigation("DepartureCities");
                });
#pragma warning restore 612, 618
        }
    }
}
